// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1281: (x0,x1) => x0.canShare(x1),
      _1282: (x0,x1) => x0.share(x1),
      _1285: (x0,x1) => ({files: x0,text: x1}),
      _1287: x0 => ({files: x0}),
      _1289: x0 => ({text: x0}),
      _1290: (x0,x1) => x0.createElement(x1),
      _1291: x0 => x0.click(),
      _1292: x0 => x0.remove(),
      _1293: () => ({}),
      _1294: (x0,x1,x2) => new File(x0,x1,x2),
      _1295: x0 => globalThis.URL.revokeObjectURL(x0),
      _1296: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      _1298: x0 => globalThis.URL.createObjectURL(x0),
      _1299: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1299(f,arguments.length,x0) }),
      _1300: (x0,x1,x2,x3) => x0.toBlob(x1,x2,x3),
      _1301: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1301(f,arguments.length,x0) }),
      _1302: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1302(f,arguments.length,x0) }),
      _1303: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1303(f,arguments.length,x0) }),
      _1304: (x0,x1) => x0.querySelector(x1),
      _1305: (x0,x1) => x0.append(x1),
      _1306: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1307: (x0,x1) => x0.replaceChildren(x1),
      _1312: () => globalThis.listenForPaste(),
      _1318: (x0,x1) => x0.createElement(x1),
      _1324: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1325: x0 => x0.onAdd(),
      _1326: (x0,x1) => x0.clearMarkers(x1),
      _1327: x0 => x0.onRemove(),
      _1328: x0 => x0.render(),
      _1329: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1329(f,arguments.length,x0,x1,x2) }),
      _1330: (x0,x1,x2) => ({map: x0,markers: x1,onClusterClick: x2}),
      _1343: x0 => new markerClusterer.MarkerClusterer(x0),
      _1345: (x0,x1,x2) => x0.addMarkers(x1,x2),
      _1347: (x0,x1,x2) => x0.removeMarkers(x1,x2),
      _1353: (x0,x1) => new google.maps.Map(x0,x1),
      _1355: (x0,x1,x2) => x0.set(x1,x2),
      _1356: () => ({}),
      _1359: x0 => x0.close(),
      _1360: (x0,x1,x2) => x0.open(x1,x2),
      _1361: x0 => new google.maps.InfoWindow(x0),
      _1362: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1362(f,arguments.length,x0) }),
      _1363: x0 => new google.maps.Marker(x0),
      _1364: x0 => new google.maps.marker.AdvancedMarkerElement(x0),
      _1366: (x0,x1) => new google.maps.Size(x0,x1),
      _1367: x0 => new Blob(x0),
      _1370: (x0,x1) => x0.removeAt(x1),
      _1373: x0 => new google.maps.Polyline(x0),
      _1374: () => ({}),
      _1377: (x0,x1) => new google.maps.LatLng(x0,x1),
      _1378: () => ({}),
      _1380: (x0,x1) => x0.appendChild(x1),
      _1381: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1381(f,arguments.length,x0) }),
      _1382: x0 => ({createHTML: x0}),
      _1383: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1384: (x0,x1) => x0.createHTML(x1),
      _1385: () => ({}),
      _1389: () => ({}),
      _1391: () => ({}),
      _1396: () => ({}),
      _1402: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1403: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1409: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1410: x0 => ({type: x0}),
      _1411: (x0,x1) => new Blob(x0,x1),
      _1412: (x0,x1) => x0.getElementById(x1),
      _1413: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1414: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1414(f,arguments.length,x0) }),
      _1415: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1416: () => ({}),
      _1417: x0 => globalThis.pdfjsLib.getDocument(x0),
      _1418: (x0,x1) => x0.getContext(x1),
      _1419: (x0,x1) => x0.getPage(x1),
      _1420: (x0,x1) => x0.getViewport(x1),
      _1421: (x0,x1) => x0.render(x1),
      _1422: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1422(f,arguments.length,x0) }),
      _1423: (x0,x1) => x0.toBlob(x1),
      _1424: () => new FileReader(),
      _1425: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1426: x0 => x0.cleanup(),
      _1427: x0 => x0.destroy(),
      _1428: (x0,x1) => { x0.module = x1 },
      _1429: (x0,x1) => { x0.exports = x1 },
      _1430: x0 => x0.decode(),
      _1431: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1432: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1433: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1433(f,arguments.length,x0) }),
      _1434: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1434(f,arguments.length,x0) }),
      _1435: x0 => x0.send(),
      _1436: () => new XMLHttpRequest(),
      _1437: (x0,x1) => x0.getItem(x1),
      _1438: (x0,x1) => x0.removeItem(x1),
      _1439: (x0,x1,x2) => x0.setItem(x1,x2),
      _1440: (x0,x1) => x0.item(x1),
      _1442: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1442(f,arguments.length,x0) }),
      _1443: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1443(f,arguments.length,x0) }),
      _1444: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1444(f,arguments.length,x0) }),
      _1445: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1445(f,arguments.length,x0) }),
      _1446: (x0,x1) => x0.removeChild(x1),
      _1448: Date.now,
      _1450: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1451: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1452: () => new Error().stack,
      _1453: () => typeof dartUseDateNowForTicks !== "undefined",
      _1454: () => 1000 * performance.now(),
      _1455: () => Date.now(),
      _1456: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1457: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1458: () => new WeakMap(),
      _1459: (map, o) => map.get(o),
      _1460: (map, o, v) => map.set(o, v),
      _1461: (exn) => exn.toString(),
      _1462: (exn) => exn.stack,
      _1463: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1464: x0 => new WeakRef(x0),
      _1465: x0 => x0.deref(),
      _1472: () => globalThis.WeakRef,
      _1475: s => JSON.stringify(s),
      _1476: s => printToConsole(s),
      _1477: (o, p, r) => o.replaceAll(p, () => r),
      _1478: (o, p, r) => o.replace(p, () => r),
      _1479: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1480: s => s.toUpperCase(),
      _1481: s => s.trim(),
      _1482: s => s.trimLeft(),
      _1483: s => s.trimRight(),
      _1484: (string, times) => string.repeat(times),
      _1485: Function.prototype.call.bind(String.prototype.indexOf),
      _1486: (s, p, i) => s.lastIndexOf(p, i),
      _1487: (string, token) => string.split(token),
      _1488: Object.is,
      _1491: (o, t) => typeof o === t,
      _1492: (o, c) => o instanceof c,
      _1493: o => Object.keys(o),
      _1496: (o, a) => o + a,
      _1523: x0 => new Array(x0),
      _1525: x0 => x0.length,
      _1527: (x0,x1) => x0[x1],
      _1528: (x0,x1,x2) => { x0[x1] = x2 },
      _1531: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1533: x0 => new Int8Array(x0),
      _1534: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1536: x0 => new Uint8ClampedArray(x0),
      _1538: x0 => new Int16Array(x0),
      _1540: x0 => new Uint16Array(x0),
      _1542: x0 => new Int32Array(x0),
      _1544: x0 => new Uint32Array(x0),
      _1546: x0 => new Float32Array(x0),
      _1548: x0 => new Float64Array(x0),
      _1572: x0 => x0.random(),
      _1573: (x0,x1) => x0.getRandomValues(x1),
      _1574: () => globalThis.crypto,
      _1575: () => globalThis.Math,
      _1588: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1589: (handle) => clearTimeout(handle),
      _1590: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1591: (handle) => clearInterval(handle),
      _1592: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1593: () => Date.now(),
      _1594: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1595: (x0,x1) => x0.exec(x1),
      _1596: (x0,x1) => x0.test(x1),
      _1597: x0 => x0.pop(),
      _1599: o => o === undefined,
      _1601: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1603: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1604: o => o instanceof RegExp,
      _1605: (l, r) => l === r,
      _1606: o => o,
      _1607: o => o,
      _1608: o => o,
      _1609: b => !!b,
      _1610: o => o.length,
      _1612: (o, i) => o[i],
      _1613: f => f.dartFunction,
      _1614: () => ({}),
      _1615: () => [],
      _1617: () => globalThis,
      _1618: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1620: (o, p) => o[p],
      _1621: (o, p, v) => o[p] = v,
      _1622: (o, m, a) => o[m].apply(o, a),
      _1624: o => String(o),
      _1625: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1626: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1626(f,arguments.length,x0) }),
      _1627: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1627(f,arguments.length,x0,x1) }),
      _1628: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1629: o => [o],
      _1630: (o0, o1) => [o0, o1],
      _1631: (o0, o1, o2) => [o0, o1, o2],
      _1632: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1633: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1634: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1635: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1636: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1637: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1638: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1639: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1640: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1641: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1642: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1643: x0 => new ArrayBuffer(x0),
      _1644: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1646: x0 => x0.index,
      _1648: x0 => x0.flags,
      _1649: x0 => x0.multiline,
      _1650: x0 => x0.ignoreCase,
      _1651: x0 => x0.unicode,
      _1652: x0 => x0.dotAll,
      _1653: (x0,x1) => { x0.lastIndex = x1 },
      _1654: (o, p) => p in o,
      _1655: (o, p) => o[p],
      _1656: (o, p, v) => o[p] = v,
      _1691: (x0,x1,x2) => globalThis.google.maps.event.addListener(x0,x1,x2),
      _1692: x0 => x0.remove(),
      _2064: x0 => x0.overlayMapTypes,
      _2067: x0 => x0.getCenter(),
      _2071: x0 => x0.getHeading(),
      _2079: x0 => x0.getTilt(),
      _2081: x0 => x0.getZoom(),
      _2089: (x0,x1) => x0.setOptions(x1),
      _2095: (module,f) => finalizeWrapper(f, function() { return module.exports._2095(f,arguments.length) }),
      _2097: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2097(f,arguments.length,x0) }),
      _2104: (module,f) => finalizeWrapper(f, function() { return module.exports._2104(f,arguments.length) }),
      _2113: (module,f) => finalizeWrapper(f, function() { return module.exports._2113(f,arguments.length) }),
      _2116: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2116(f,arguments.length,x0) }),
      _2117: x0 => x0.latLng,
      _2163: x0 => x0.latLng,
      _2170: (x0,x1) => { x0.cameraControl = x1 },
      _2174: (x0,x1) => { x0.center = x1 },
      _2192: (x0,x1) => { x0.fullscreenControl = x1 },
      _2195: (x0,x1) => { x0.gestureHandling = x1 },
      _2208: (x0,x1) => { x0.mapId = x1 },
      _2210: (x0,x1) => { x0.mapTypeControl = x1 },
      _2214: (x0,x1) => { x0.mapTypeId = x1 },
      _2216: (x0,x1) => { x0.maxZoom = x1 },
      _2218: (x0,x1) => { x0.minZoom = x1 },
      _2229: x0 => x0.rotateControl,
      _2230: (x0,x1) => { x0.rotateControl = x1 },
      _2242: (x0,x1) => { x0.streetViewControl = x1 },
      _2245: (x0,x1) => { x0.styles = x1 },
      _2248: (x0,x1) => { x0.tilt = x1 },
      _2252: (x0,x1) => { x0.zoom = x1 },
      _2254: (x0,x1) => { x0.zoomControl = x1 },
      _2262: () => globalThis.google.maps.MapTypeId.HYBRID,
      _2263: () => globalThis.google.maps.MapTypeId.ROADMAP,
      _2264: () => globalThis.google.maps.MapTypeId.SATELLITE,
      _2265: () => globalThis.google.maps.MapTypeId.TERRAIN,
      _2270: (x0,x1) => { x0.stylers = x1 },
      _2272: (x0,x1) => { x0.elementType = x1 },
      _2274: (x0,x1) => { x0.featureType = x1 },
      _2302: (x0,x1) => { x0.collisionBehavior = x1 },
      _2306: (x0,x1) => { x0.gmpDraggable = x1 },
      _2307: x0 => x0.map,
      _2308: (x0,x1) => { x0.map = x1 },
      _2310: (x0,x1) => { x0.position = x1 },
      _2312: (x0,x1) => { x0.title = x1 },
      _2314: (x0,x1) => { x0.zIndex = x1 },
      _2318: (x0,x1) => { x0.content = x1 },
      _2322: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2322(f,arguments.length,x0) }),
      _2323: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2323(f,arguments.length,x0) }),
      _2324: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2324(f,arguments.length,x0) }),
      _2325: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2325(f,arguments.length,x0) }),
      _2327: x0 => x0.collisionBehavior,
      _2329: x0 => x0.content,
      _2331: x0 => x0.gmpDraggable,
      _2335: x0 => x0.position,
      _2337: x0 => x0.title,
      _2339: x0 => x0.zIndex,
      _2531: (x0,x1) => x0.setMap(x1),
      _2532: (x0,x1) => x0.setOptions(x1),
      _2534: (x0,x1) => x0.setVisible(x1),
      _2535: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2535(f,arguments.length,x0) }),
      _2549: (x0,x1) => { x0.clickable = x1 },
      _2555: (x0,x1) => { x0.geodesic = x1 },
      _2561: (x0,x1) => { x0.path = x1 },
      _2562: (x0,x1) => { x0.strokeColor = x1 },
      _2565: (x0,x1) => { x0.strokeOpacity = x1 },
      _2567: (x0,x1) => { x0.strokeWeight = x1 },
      _2569: (x0,x1) => { x0.visible = x1 },
      _2571: (x0,x1) => { x0.zIndex = x1 },
      _2953: x0 => x0.lat(),
      _2954: x0 => x0.lng(),
      _3952: (x0,x1) => x0.setContent(x1),
      _3977: x0 => x0.content,
      _3978: (x0,x1) => { x0.content = x1 },
      _3994: (x0,x1) => { x0.zIndex = x1 },
      _4098: (x0,x1) => { x0.url = x1 },
      _4106: (x0,x1) => { x0.scaledSize = x1 },
      _4108: (x0,x1) => { x0.size = x1 },
      _4116: x0 => x0.getMap(),
      _4129: (x0,x1) => x0.setMap(x1),
      _4131: (x0,x1) => x0.setOptions(x1),
      _4132: (x0,x1) => x0.setPosition(x1),
      _4138: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4138(f,arguments.length,x0) }),
      _4143: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4143(f,arguments.length,x0) }),
      _4144: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4144(f,arguments.length,x0) }),
      _4146: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4146(f,arguments.length,x0) }),
      _4184: (x0,x1) => { x0.draggable = x1 },
      _4186: (x0,x1) => { x0.icon = x1 },
      _4192: (x0,x1) => { x0.opacity = x1 },
      _4196: (x0,x1) => { x0.position = x1 },
      _4200: (x0,x1) => { x0.title = x1 },
      _4202: (x0,x1) => { x0.visible = x1 },
      _4204: (x0,x1) => { x0.zIndex = x1 },
      _4261: () => new XMLHttpRequest(),
      _4262: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _4266: x0 => x0.send(),
      _4268: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4268(f,arguments.length,x0) }),
      _4269: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4269(f,arguments.length,x0) }),
      _4274: (x0,x1) => new WebSocket(x0,x1),
      _4275: (x0,x1) => x0.send(x1),
      _4276: (x0,x1,x2) => x0.close(x1,x2),
      _4277: (x0,x1) => x0.close(x1),
      _4278: x0 => x0.close(),
      _4281: x0 => new BroadcastChannel(x0),
      _4282: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4282(f,arguments.length,x0) }),
      _4283: (x0,x1) => x0.postMessage(x1),
      _4284: x0 => x0.close(),
      _4285: () => new AbortController(),
      _4286: x0 => x0.abort(),
      _4287: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _4288: (x0,x1) => globalThis.fetch(x0,x1),
      _4289: (x0,x1) => x0.get(x1),
      _4290: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._4290(f,arguments.length,x0,x1,x2) }),
      _4291: (x0,x1) => x0.forEach(x1),
      _4292: x0 => x0.getReader(),
      _4293: x0 => x0.cancel(),
      _4294: x0 => x0.read(),
      _4295: (x0,x1) => x0.key(x1),
      _4297: (x0,x1) => { x0.data = x1 },
      _4298: (x0,x1) => { x0.scale = x1 },
      _4299: (x0,x1) => { x0.canvasContext = x1 },
      _4300: (x0,x1) => { x0.viewport = x1 },
      _4301: (x0,x1) => { x0.cMapUrl = x1 },
      _4302: (x0,x1) => { x0.cMapPacked = x1 },
      _4303: x0 => x0.promise,
      _4304: x0 => x0.numPages,
      _4305: x0 => x0.width,
      _4306: x0 => x0.height,
      _4307: x0 => x0.promise,
      _4308: x0 => x0.trustedTypes,
      _4309: (x0,x1) => { x0.innerHTML = x1 },
      _4310: (x0,x1) => { x0.innerHTML = x1 },
      _4311: o => o instanceof Array,
      _4312: (a, i) => a.push(i),
      _4316: a => a.pop(),
      _4317: (a, i) => a.splice(i, 1),
      _4319: (a, s, e) => a.slice(s, e),
      _4321: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _4322: a => a.length,
      _4324: (a, i) => a[i],
      _4325: (a, i, v) => a[i] = v,
      _4327: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _4328: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _4330: o => o instanceof Uint8Array,
      _4331: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _4332: o => o instanceof Int8Array,
      _4333: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _4334: o => o instanceof Uint8ClampedArray,
      _4335: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _4336: o => o instanceof Uint16Array,
      _4337: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _4338: o => o instanceof Int16Array,
      _4339: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _4340: o => o instanceof Uint32Array,
      _4341: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _4342: o => o instanceof Int32Array,
      _4343: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _4345: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _4346: o => o instanceof Float32Array,
      _4347: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _4348: o => o instanceof Float64Array,
      _4349: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _4350: (t, s) => t.set(s),
      _4351: l => new DataView(new ArrayBuffer(l)),
      _4352: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _4353: o => o.byteLength,
      _4354: o => o.buffer,
      _4355: o => o.byteOffset,
      _4356: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _4357: (b, o) => new DataView(b, o),
      _4358: (b, o, l) => new DataView(b, o, l),
      _4359: Function.prototype.call.bind(DataView.prototype.getUint8),
      _4360: Function.prototype.call.bind(DataView.prototype.setUint8),
      _4361: Function.prototype.call.bind(DataView.prototype.getInt8),
      _4362: Function.prototype.call.bind(DataView.prototype.setInt8),
      _4363: Function.prototype.call.bind(DataView.prototype.getUint16),
      _4364: Function.prototype.call.bind(DataView.prototype.setUint16),
      _4365: Function.prototype.call.bind(DataView.prototype.getInt16),
      _4366: Function.prototype.call.bind(DataView.prototype.setInt16),
      _4367: Function.prototype.call.bind(DataView.prototype.getUint32),
      _4368: Function.prototype.call.bind(DataView.prototype.setUint32),
      _4369: Function.prototype.call.bind(DataView.prototype.getInt32),
      _4370: Function.prototype.call.bind(DataView.prototype.setInt32),
      _4373: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _4374: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _4375: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _4376: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _4377: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _4378: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _4379: Function.prototype.call.bind(Number.prototype.toString),
      _4380: Function.prototype.call.bind(BigInt.prototype.toString),
      _4381: Function.prototype.call.bind(Number.prototype.toString),
      _4382: (d, digits) => d.toFixed(digits),
      _4480: () => globalThis.document,
      _4486: (x0,x1) => { x0.height = x1 },
      _4488: (x0,x1) => { x0.width = x1 },
      _4490: (x0,x1) => { x0.pointerEvents = x1 },
      _4499: x0 => x0.style,
      _4502: x0 => x0.src,
      _4503: (x0,x1) => { x0.src = x1 },
      _4504: x0 => x0.naturalWidth,
      _4505: x0 => x0.naturalHeight,
      _4521: x0 => x0.status,
      _4522: (x0,x1) => { x0.responseType = x1 },
      _4524: x0 => x0.response,
      _4580: (x0,x1) => { x0.responseType = x1 },
      _4581: x0 => x0.response,
      _4641: (x0,x1) => { x0.draggable = x1 },
      _4647: (x0,x1) => { x0.innerText = x1 },
      _4657: x0 => x0.style,
      _4670: (x0,x1) => { x0.oncancel = x1 },
      _4676: (x0,x1) => { x0.onchange = x1 },
      _4678: (x0,x1) => { x0.onclick = x1 },
      _4716: (x0,x1) => { x0.onerror = x1 },
      _5014: (x0,x1) => { x0.target = x1 },
      _5016: (x0,x1) => { x0.download = x1 },
      _5041: (x0,x1) => { x0.href = x1 },
      _5089: (x0,x1) => { x0.src = x1 },
      _5100: x0 => x0.width,
      _5102: x0 => x0.height,
      _5586: (x0,x1) => { x0.accept = x1 },
      _5600: x0 => x0.files,
      _5626: (x0,x1) => { x0.multiple = x1 },
      _5644: (x0,x1) => { x0.type = x1 },
      _5894: (x0,x1) => { x0.src = x1 },
      _5896: (x0,x1) => { x0.type = x1 },
      _5900: (x0,x1) => { x0.async = x1 },
      _5938: x0 => x0.width,
      _5939: (x0,x1) => { x0.width = x1 },
      _5940: x0 => x0.height,
      _5941: (x0,x1) => { x0.height = x1 },
      _6362: () => globalThis.window,
      _6402: x0 => x0.document,
      _6405: x0 => x0.location,
      _6424: x0 => x0.navigator,
      _6686: x0 => x0.trustedTypes,
      _6688: x0 => x0.localStorage,
      _6696: x0 => x0.href,
      _6811: x0 => x0.userAgent,
      _6812: x0 => x0.vendor,
      _6862: x0 => x0.data,
      _6909: (x0,x1) => { x0.onmessage = x1 },
      _7016: x0 => x0.length,
      _7233: x0 => x0.readyState,
      _7246: (x0,x1) => { x0.binaryType = x1 },
      _7249: x0 => x0.code,
      _7250: x0 => x0.reason,
      _8917: x0 => x0.type,
      _8918: x0 => x0.target,
      _8958: x0 => x0.signal,
      _9019: x0 => x0.firstChild,
      _9030: () => globalThis.document,
      _9111: x0 => x0.body,
      _9113: x0 => x0.head,
      _9442: (x0,x1) => { x0.id = x1 },
      _9444: (x0,x1) => { x0.className = x1 },
      _9466: (x0,x1) => { x0.innerHTML = x1 },
      _9469: x0 => x0.children,
      _10788: x0 => x0.value,
      _10790: x0 => x0.done,
      _10970: x0 => x0.size,
      _10971: x0 => x0.type,
      _10974: (x0,x1) => { x0.type = x1 },
      _10977: x0 => x0.name,
      _10978: x0 => x0.lastModified,
      _10983: x0 => x0.length,
      _10988: x0 => x0.result,
      _11485: x0 => x0.url,
      _11487: x0 => x0.status,
      _11489: x0 => x0.statusText,
      _11490: x0 => x0.headers,
      _11491: x0 => x0.body,
      _13897: (x0,x1) => { x0.display = x1 },
      _14061: (x0,x1) => { x0.height = x1 },
      _14751: (x0,x1) => { x0.width = x1 },
      _15119: x0 => x0.name,
      _15120: x0 => x0.message,
      _15861: (x0,x1,x2,x3,x4,x5,x6,x7) => ({hue: x0,lightness: x1,saturation: x2,gamma: x3,invert_lightness: x4,visibility: x5,color: x6,weight: x7}),

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
